services:

  webserver:
    container_name: webserver
    build: .
    volumes:
      - "./.nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf"
      - "./src:/usr/share/nginx/html:ro"
      - "./vault:/usr/share/nginx/html/vault:ro"
    ports:
      - "3000:3000"
